spring.application.name=E-Commerce-System

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=12345
spring.datasource.username=postgres

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

security.jwt.secret-key=dGVzdFRva2VuU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Ng==


spring.data.redis.host = localhost
spring.data.redis.port = 6379






